### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PyTorr** [TimmHess/UnrealImageCapture#12]
Hi,
I downloaded your project, compiled it and tried to run it.
But when I press `C` the game crush with no apparent error.
Do you know why?

**Comment by TimmHess** [comment]
Hey, 

without any additional information, unfortunately, this won't be possible. 
Did you look at the error report in your crash client? Or can you send me the crash log? Maybe then I will find the problem.

**Comment by PyTorr** [comment]
Thanks for the quick reply.
Unreal get stuck with no log.

What I did is to build the `capturedisk` folder with unreal 4.26.2 .
Then I press play everything works fine.
Then I press `c` and everything crush.

**Comment by TimmHess** [comment]
I just tried to reproduce your issue with a fresh clone in version 4.26.2. However, I could not reproduce, all capturing modes worked fine for me. 

Just to be sure I understand correctly: Does the project **crash**, meaning the engine shuts down automatically? Or does it **freeze**, meaning you have to shut it down by yourself because it does not respond anymore?

Also, could you look into your CaptureToDisk/Saved/Logs/CaptureToDisk.log file immediately after the "crash" (without restarting the engine first)? There you should be able to find an error message.

**Comment by PyTorr** [comment]
I will get back to you.
Thanks for the help.

**Comment by PyTorr** [comment]
Hi,
Sometimes it freezes and I need to close it manually.

Usually though it crashes.

I attached the log.
[CaptureToDisk.log](https://github.com/TimmHess/UnrealImageCapture/files/6806884/CaptureToDisk.log)

**Comment by PyTorr** [comment]
I cloned the project instead of downloading it and now it works.
Thank you for all the help.

Why it saves `exr` files?

**Comment by TimmHess** [comment]
That is definitely weired..
The last update included depth data to be stored. Therefor you need an imaging format that supports either float values or values way higher than usual 255 information. Otherwise, your "resolution" in depth is very restricted. The .exr format is one such format.

To get color images, see the CaptureManager in the editor's world-outline and switch off float value saving format. Also you will want to remove/clear the post process material. 

Finally, in the blueprint where you call the CaptureManager (which is currently the level blueprint) switch the function call from `CaptureFloatNonBlocking` to `CaptureNonBlocking`. 

Maybe I will unify these calls soon.. having them split feels like an artifact from an ealier implementation where depth capture was broken...

**Comment by PyTorr** [comment]
Ok I recloned the project.

Now the depth works great, but I can't get RGB image again.

**Comment by TimmHess** [comment]
Maybe the issue is that you are using a single CaptureManager? You need a separate `CaptureManager `and respective `SceneCaptureComponent `for each modality you want to capture.

For example, if you call `CaptureNonBlocking` with Float capture ticked on, you will receive an error message in the output log.
Again, maybe I should change this to a unified function as well...

**Comment by PyTorr** [comment]
Yes, now everything is working 😁.

**Comment by TimmHess** [comment]
Awesome!
