### ISSUE TITLE
Crash when using depth

### ISSUE THREAD

**Issue by lgk50** [TimmHess/UnrealImageCapture#21]
Dear TimmHess

Thanks for your code! I am trying to use your plugin to obtain scene depth but crashes every time when I tried to capture depth image.  

I am using UE5.03 and created a blank C++ project.  I added the UE5 plugin to the project, add the CameraCaptureManager_BP to the scene, and added a SceneCapture2D as capture component, used PP_depth as the material
![image](https://user-images.githubusercontent.com/33919293/202326117-25a45a17-b182-4d60-b368-8c5d4705f6c8.png)
The level  blueprint is shown as follow.
![image](https://user-images.githubusercontent.com/33919293/202326195-5bacf189-66fa-4ea0-9790-43b95a0bfa3d.png)

When I tried to capture depth, the UE crashed at line
imageWrapper->SetRaw(nextRenderRequest->Image.GetData(), nextRenderRequest->Image.GetAllocatedSize(), FrameWidth, FrameHeight, ERGBFormat::BGRA, 16);

I got the error. Assertion failed: (int64)ChannelCount * Width * Height * RawBitDepth == RawData.Num() * 8
I am check the image size using  nextRenderRequest->Image.GetAllocatedSize(), it returns 2457600 = 640x480x8.  should that be 640x480x8x4 since there are RGBA 4 channels? 

I really hope you can shed light on my question and help me here, I've been struggling for last 2 days.

Your help is really appreciated!

**Comment by TimmHess** [comment]
Hi,

thank you very much for the detailed explanation! I am so sorry - this project is in utterly terrible shape. 

**However**, I finally got around - the issue is that in UE5 you actually can make a distinction for 'float' values in ERGBFormat, namely changing `ERGBFormat::RGBA` -> `ERGBFormat::RGBAF`. (Seems someone did not properly test for that *cough*)
This resolved the crash. Also, I viewed the .exr file using python and OpenEXR and that gave the expected result.

I will do a push shortly, but you can also swiftly at the missing **F**.

Hope this resolve the mess for you. 👍

**Comment by lgk50** [comment]
Thank you TimmHess!  It fixed my issue, I was able to generate exr in UE5 now.

Really appreciate your help!
