### ISSUE TITLE
Plugin version?

### ISSUE THREAD

**Issue by Noelok** [TimmHess/UnrealImageCapture#4]
Hi, 
I'd like to know if it would be difficult to create a plugin from your code?
I'm using blueprints (I'm not a coder), and I think it would be great to have a plugin that could let the users choose the outputs they need (ground truth, semantic segmentation, depth, normals...).
I can't use UnrealCV anymore (no more update), so your code could be a great alternative!
Best,
n.

**Comment by TimmHess** [comment]
Hi, 
actually, I just never tried.. but I would imagine it to be very much doable. It is definitely on my list, I just did not come to it.
Maybe I get to it in the next few weeks, however, I do not want to promise anything

**Comment by Noelok** [comment]
Thank you TimmHess!
Let me know if I can help if you do it. I can test it on Mac if you need to.

**Comment by TimmHess** [comment]
Oh great, thanks!
I will come back to you :)

**Comment by TimmHess** [comment]
Hey, I just merged the Plugin branch into master. However, I can not compile for iOS because I do not own a Mac... I guess you will need to do that yourself. 
If you try: remember to remove  
"WhitelistPlatforms": [
				"Win64"
			]
from CaptureToDisk/Plugins/CameraCaptureToDisk/CameraCaptureToDisk.uplugin

After that, you could just start an empty c++ project, copy the plugin, and package it for iOS to be usable in your blueprint projects :)
